cors:
  origins:
    - '*'
  methods:
    - GET
    - POST
    - PUT
    - PATCH
    - OPTIONS
    - DELETE
  headers:
    - Origin
    - X-Requested-With
    - Content-Type
    - Accept
    - Authorization
